export type TAuthActions = {
  SET_IS_AUTH: "SET_IS_AUTH";
  RESET_IS_AUTH: "RESET_IS_AUTH";
  REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST";
  REFRESH_TOKEN_REQUEST_SUCCESS: "REFRESH_TOKEN_REQUEST_SUCCESS";
  REFRESH_TOKEN_REQUEST_FAILED: 'REFRESH_TOKEN_REQUEST_FAILED';
  LOGIN_REQUEST: 'LOGIN_REQUEST';
  LOGIN_REQUEST_REQUEST_SUCCESS: 'LOGIN_REQUEST_REQUEST_SUCCESS';
  LOGIN_REQUEST_REQUEST_FAILED: 'LOGIN_REQUEST_REQUEST_FAILED';
  LOGOUT_REQUEST: 'LOGOUT_REQUEST';
  LOGOUT_REQUEST_REQUEST_SUCCESS: 'LOGOUT_REQUEST_REQUEST_SUCCESS';
  LOGOUT_REQUEST_REQUEST_FAILED: 'LOGOUT_REQUEST_REQUEST_FAILED';
}